"""catagory

Revision ID: 932e3db7fdd7
Revises: 6092228cc420
Create Date: 2024-04-14 14:49:50.967360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '932e3db7fdd7'
down_revision = '6092228cc420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catagory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catagory')
    # ### end Alembic commands ###
