"""empty message

Revision ID: b50b9f41a86d
Revises: 72072e5b9bd0
Create Date: 2024-04-21 20:07:14.084433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b50b9f41a86d'
down_revision = '72072e5b9bd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PostCity',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'city_id')
    )
    op.create_table('PostTag',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'tag_id')
    )
    op.drop_table('post_city')
    op.drop_table('post_tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tag',
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='post_tag_post_id_fkey'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name='post_tag_tag_id_fkey'),
    sa.PrimaryKeyConstraint('post_id', 'tag_id', name='post_tag_pkey')
    )
    op.create_table('post_city',
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('city_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], name='post_city_city_id_fkey'),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='post_city_post_id_fkey'),
    sa.PrimaryKeyConstraint('post_id', 'city_id', name='post_city_pkey')
    )
    op.drop_table('PostTag')
    op.drop_table('PostCity')
    # ### end Alembic commands ###
