"""empty message

Revision ID: dc7de085bc3e
Revises: ebb02f8f53ce
Create Date: 2024-04-21 20:35:24.957046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc7de085bc3e'
down_revision = 'ebb02f8f53ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_city')
    op.drop_table('post_tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tag',
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='post_tag_post_id_fkey'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name='post_tag_tag_id_fkey'),
    sa.PrimaryKeyConstraint('post_id', 'tag_id', name='post_tag_pkey')
    )
    op.create_table('post_city',
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('city_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], name='post_city_city_id_fkey'),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='post_city_post_id_fkey'),
    sa.PrimaryKeyConstraint('post_id', 'city_id', name='post_city_pkey')
    )
    # ### end Alembic commands ###
