"""empty message

Revision ID: e61d018a38e2
Revises: 932e3db7fdd7
Create Date: 2024-04-21 18:30:21.546088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e61d018a38e2'
down_revision = '932e3db7fdd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('city_introduction',
    sa.Column('city_name', sa.String(length=50), nullable=False),
    sa.Column('introduction', sa.Text(), nullable=True),
    sa.Column('useful_links', sa.Text(), nullable=True),
    sa.Column('emergency_help', sa.Text(), nullable=True),
    sa.Column('transportation_info', sa.Text(), nullable=True),
    sa.Column('climate', sa.Text(), nullable=True),
    sa.Column('festivals', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('related_content', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['city_name'], ['city.name'], ),
    sa.PrimaryKeyConstraint('city_name')
    )
    op.drop_table('catagory')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tag_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tag', ['tag_id'], ['id'])
        batch_op.create_foreign_key(None, 'city', ['city_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tag_id')
        batch_op.drop_column('city_id')

    op.create_table('catagory',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='catagory_pkey'),
    sa.UniqueConstraint('name', name='catagory_name_key')
    )
    op.drop_table('city_introduction')
    op.drop_table('city')
    op.drop_table('tag')
    op.drop_table('country')
    # ### end Alembic commands ###
