"""empty message

Revision ID: ebb02f8f53ce
Revises: b50b9f41a86d
Create Date: 2024-04-21 20:11:47.534475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebb02f8f53ce'
down_revision = 'b50b9f41a86d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_city',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'city_id')
    )
    op.create_table('post_tag',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'tag_id')
    )
    op.drop_table('PostCity')
    op.drop_table('PostTag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PostTag',
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='PostTag_post_id_fkey'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name='PostTag_tag_id_fkey'),
    sa.PrimaryKeyConstraint('post_id', 'tag_id', name='PostTag_pkey')
    )
    op.create_table('PostCity',
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('city_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], name='PostCity_city_id_fkey'),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='PostCity_post_id_fkey'),
    sa.PrimaryKeyConstraint('post_id', 'city_id', name='PostCity_pkey')
    )
    op.drop_table('post_tag')
    op.drop_table('post_city')
    # ### end Alembic commands ###
