"""add the CityIntroduction table

Revision ID: fa7c13a00f12
Revises: 6a343198a88f
Create Date: 2024-04-18 19:49:25.218491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa7c13a00f12'
down_revision = '6a343198a88f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city_introduction',
    sa.Column('city_name', sa.String(length=50), nullable=False),
    sa.Column('introduction', sa.Text(), nullable=True),
    sa.Column('useful_links', sa.Text(), nullable=True),
    sa.Column('emergency_help', sa.Text(), nullable=True),
    sa.Column('transportation_info', sa.Text(), nullable=True),
    sa.Column('climate', sa.Text(), nullable=True),
    sa.Column('festivals', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('related_content', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['city_name'], ['city.name'], ),
    sa.PrimaryKeyConstraint('city_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('city_introduction')
    # ### end Alembic commands ###
